### ISSUE TITLE
Publish a Github release

### ISSUE THREAD

**Issue by jaredledvina** [devshane/zork#3]
Hey @devshane,

Thanks so much for hosting this project on your account. I was hoping to create a Homebrew formula but, need a release to point formula to (https://github.com/Homebrew/homebrew-core/pull/14681).

Is there any chance you'd be willing to [cut a Github release](https://help.github.com/articles/creating-releases/) on this project? 

What version number you chose, I'll update my Homebrew formula to match.

**Comment by devshane** [comment]
Hey @jaredledvina, I'm happy to be a small part of the Zork legacy. I published a 1.0.0 -- it seems like the code's baked long enough to warrant at least that.

https://github.com/devshane/zork/releases/tag/v1.0.0

**Comment by jaredledvina** [comment]
\o/
Thanks @devshane! Works perfectly!
